CREATE TABLE "JADLOSPIS_BC_01"."NAP_USERS"
(	"USERNAME" VARCHAR2(100 BYTE),
     "NAME" VARCHAR2(100 BYTE),
     "HASHEDPASSWORD" VARCHAR2(500 BYTE),
     "ID" NUMBER,
     "OPERATOR_ID" NUMBER,
     CONSTRAINT "NAP_USERS_PK" UNIQUE ("ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "JADLOSPI_BC_DATA_1"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JADLOSPI_BC_DATA_1" ;